#!/bin/sh

# THIS  FILE CAN BE DELETED AND THE DOCKERFILE CHANGED TO RUN SERVER START INSTEAD
# ALEMVIC DOESNT WORK BECAUSE THE CONTAINER IS NOT FULLY SETUP AT THIS POINT
alembic upgrade head
echo "DEBUG: alembic run"
fastapi dev main.py --host 0.0.0.0 --port 8000