"""added headshot_url to player table

Revision ID: 013f0c4a3d3a
Revises: ab4ab7acaf6e
Create Date: 2026-04-22 22:01:32.849104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '013f0c4a3d3a'
down_revision: Union[str, Sequence[str], None] = 'ab4ab7acaf6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('headshot_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'headshot_url')
    # ### end Alembic commands ###
