"""Create simpilfied schema

Revision ID: 18351c023798
Revises: 
Create Date: 2026-04-16 19:51:10.235605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '18351c023798'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playertest',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nil', sa.Integer(), nullable=True),
    sa.Column('delta_nil', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('team',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('sport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('school', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color_hex_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('game',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('away_id', sa.Integer(), nullable=False),
    sa.Column('home_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['away_id'], ['team.team_id'], ),
    sa.ForeignKeyConstraint(['home_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('player',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('college_year', sa.Enum('Freshman', 'Sophomore', 'Junior', 'Senior', name='collegeyear'), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('hometown', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('homestate', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sa.Enum('Quaterback', 'Runningback', 'WideReciever', 'TightEnd', 'OffensiveLine', 'DefensiveLine', 'Linebacker', 'Cornerback', 'Safety', name='positiontype'), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('performance',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('nil', sa.Integer(), nullable=False),
    sa.Column('nilt_delta', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance')
    op.drop_table('player')
    op.drop_table('game')
    op.drop_table('team')
    op.drop_table('playertest')
    # ### end Alembic commands ###
