"""deleted test player table

Revision ID: 24dab21c252a
Revises: fda098818a0a
Create Date: 2026-04-19 19:06:21.413680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '24dab21c252a'
down_revision: Union[str, Sequence[str], None] = 'fda098818a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playertest')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playertest',
    sa.Column('player_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nil', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delta_nil', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('player_id', name=op.f('playertest_pkey'))
    )
    # ### end Alembic commands ###
