"""reduced postion types to the five we are using

Revision ID: ab4ab7acaf6e
Revises: f53532a2a7f7
Create Date: 2026-04-22 01:41:46.707284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab4ab7acaf6e'
down_revision: Union[str, Sequence[str], None] = 'f53532a2a7f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
