"""initialize tables

Revision ID: e7e7a83df76d
Revises: 
Create Date: 2026-04-01 04:39:31.835945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e7e7a83df76d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust!
    college_year_enum = sa.Enum('Freshman', 'Sophomore', 'Junior', 'Senior', name='collegeyear')
    college_year_enum.create(op.get_bind(), checkfirst=True)
    position_type_enum = sa.Enum('Quaterback', 'Runningback', 'WideReciever', 'TightEnd', 
                                 'OffensiveLine', 'DefensiveLine', 'Linebacker', 
                                 'Cornerback', 'Safety', name='positiontype')
    position_type_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('player',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('college_year', sa.String(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('hometown', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('homestate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('high_school', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('playertest',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nil', sa.Integer(), nullable=True),
    sa.Column('delta_nil', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('school',
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color_hex_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('school_id')
    )
    op.create_table('sport',
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('sport_id')
    )
    op.create_table('injury',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'type', 'start_date')
    )
    op.create_table('team',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.school_id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.sport_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('game',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('away_id', sa.Integer(), nullable=False),
    sa.Column('home_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['away_id'], ['team.team_id'], ),
    sa.ForeignKeyConstraint(['home_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('position',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'team_id', 'season')
    )
    op.create_table('performance',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('nil', sa.Integer(), nullable=False),
    sa.Column('nilt_delta', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance')
    op.drop_table('position')
    op.drop_table('game')
    op.drop_table('team')
    op.drop_table('injury')
    op.drop_table('sport')
    op.drop_table('school')
    op.drop_table('playertest')
    op.drop_table('player')
    # ### end Alembic commands ###
