"""created new tables for position stats

Revision ID: f53532a2a7f7
Revises: 24dab21c252a
Create Date: 2026-04-22 01:04:08.532210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f53532a2a7f7'
down_revision: Union[str, Sequence[str], None] = '24dab21c252a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lbperformance',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('pass_breakups', sa.Integer(), nullable=False),
    sa.Column('def_ints', sa.Integer(), nullable=False),
    sa.Column('solo_tackles', sa.Integer(), nullable=False),
    sa.Column('sacks', sa.Integer(), nullable=False),
    sa.Column('tfl', sa.Integer(), nullable=False),
    sa.Column('forced_fumbles', sa.Integer(), nullable=False),
    sa.Column('total_tackles', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_table('qbperformance',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('rush_yards', sa.Integer(), nullable=False),
    sa.Column('pass_tds', sa.Integer(), nullable=False),
    sa.Column('ints', sa.Integer(), nullable=False),
    sa.Column('rush_tds', sa.Integer(), nullable=False),
    sa.Column('completion_pct', sa.Float(), nullable=False),
    sa.Column('pass_yards', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_table('sperformance',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('pass_breakups', sa.Integer(), nullable=False),
    sa.Column('def_ints', sa.Integer(), nullable=False),
    sa.Column('solo_tackles', sa.Integer(), nullable=False),
    sa.Column('fumble_recoveries', sa.Integer(), nullable=False),
    sa.Column('defensive_tds', sa.Integer(), nullable=False),
    sa.Column('forced_fumbles', sa.Integer(), nullable=False),
    sa.Column('total_tackles', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_table('teperformance',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('receiving_yards', sa.Integer(), nullable=False),
    sa.Column('receiving_tds', sa.Integer(), nullable=False),
    sa.Column('receptions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_table('wrperformance',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('receiving_yards', sa.Integer(), nullable=False),
    sa.Column('receiving_tds', sa.Integer(), nullable=False),
    sa.Column('receptions', sa.Integer(), nullable=False),
    sa.Column('yards_per_rec', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.add_column('player', sa.Column('base_nil', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'base_nil')
    op.drop_table('wrperformance')
    op.drop_table('teperformance')
    op.drop_table('sperformance')
    op.drop_table('qbperformance')
    op.drop_table('lbperformance')
    # ### end Alembic commands ###
