"""fixed performance schema

Revision ID: fda098818a0a
Revises: 18351c023798
Create Date: 2026-04-18 22:18:38.899031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fda098818a0a'
down_revision: Union[str, Sequence[str], None] = '18351c023798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance', sa.Column('nil_delta', sa.Float(), nullable=False))
    op.drop_column('performance', 'nilt_delta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance', sa.Column('nilt_delta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('performance', 'nil_delta')
    # ### end Alembic commands ###
